### ISSUE TITLE
Adding amenities to a Location from admin panel not working

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#15]
It seems that the expected value for input is an array of amenities and the passed value is amenities joined by commas (as a string).
<img width="1021" alt="screen shot 2016-03-03 at 11 10 35 pm" src="https://cloud.githubusercontent.com/assets/4345133/13503508/be3d3b06-e195-11e5-9b84-74b1a4ab746c.png">

**Comment by ananyo2012** [comment]
@shubhpatel108 It is working fine as i see.

![screenshot from 2016-03-05 19 33 56](https://cloud.githubusercontent.com/assets/10486343/13547956/e5eca1a8-e309-11e5-9f0c-7fa76c462da8.png)

![screenshot from 2016-03-05 19 36 06](https://cloud.githubusercontent.com/assets/10486343/13547957/ecb22daa-e309-11e5-8f35-46417988174c.png)

It is using the act-as-taggable-on gem. Amenities are saved as tags for both locations and nooks.

**Comment by shubhpatel108** [comment]
Apparently, my app was using old binaries. Cleaning up and upgrading the gems, did the work.

Thanks, @ananyo2012. Closing the issue for now.

**Comment by shubhpatel108** [comment]
@ananyo2012 Is it working when creating a location or nook? It does work fine when updating.
