### ISSUE TITLE
times labeled on extended view

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#153]
Could we add time labels to extended view (similar to admin nook interface)?

**Comment by shubhpatel108** [comment]
@jessyurko Shall we have labels for each day? or common for the entire week?

**Comment by jessyurko** [comment]
I think for the entire week -- something roughly like this? (in the above nook, since the lower one doesn't have a label)

![patron rev 10_23_k](https://cloud.githubusercontent.com/assets/1999174/17490615/a73eadba-5d71-11e6-8221-065b7c9e408f.jpg)

**Comment by shubhpatel108** [comment]
Added the hover-line too (on hourly basis) 😃. 
It doesn't have the label-highlighting though, as shown in the mockup.

**Comment by jessyurko** [comment]
wow, looks awesome!
