### ISSUE TITLE
hover on nook stats shows "0"

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#159]
<img width="492" alt="screen shot 2016-07-14 at 4 47 45 pm" src="https://cloud.githubusercontent.com/assets/1999174/16855396/2edac986-49e3-11e6-9fbf-6bb9eff9ed27.png">

**Comment by shubhpatel108** [comment]
@jessyurko Did you search without the date values in the filter?

**Comment by jessyurko** [comment]
yes, I should have included that -- is there a way to default to earliest available / current date as the date value bounds if a user does that?

**Comment by shubhpatel108** [comment]
Yes, we can default it to any date (for both start and end dates). Another option is to add validations so that the filter form is never submitted without the dates.

**Comment by jessyurko** [comment]
Cool. I like the idea of defaulting to whatever the earliest date is (and whatever the current date is for end date). Thanks!
