### ISSUE TITLE
Add Amenities filter on Nooks' search

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#16]
At present, only dummy text is added to the left pane.

**Comment by ananyo2012** [comment]
@shubhpatel108 The filter will come as checklist as soon as you add amenities tags to Nooks.
![screenshot from 2016-03-05 19 45 16](https://cloud.githubusercontent.com/assets/10486343/13548001/fd6c79f6-e30a-11e5-93c2-8e4c29ee2d3f.png)

**Comment by shubhpatel108** [comment]
Apparently, my app was using old binaries. Cleaning up and upgrading the gems, did the work. 

Thanks, @ananyo2012. Closing the issue for now.
