### ISSUE TITLE
adjust range for heat map

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#161]
Might improve legibility to adjust range on color key for heatmaps. e.g. for a nook with only a few reservations, red values might be at 50 rather than 200

<img width="1272" alt="screen shot 2016-07-14 at 4 55 14 pm" src="https://cloud.githubusercontent.com/assets/1999174/16855582/fc0343ac-49e3-11e6-857a-e7d433bdd02b.png">

**Comment by shubhpatel108** [comment]
We can dynamically adjust the scale from 0 to Max of the value. 
Also, I was thinking we can have a monochrome chart. In example chart, blue was used for depicting negative values (temperature) which we don't have in our data.

**Comment by shubhpatel108** [comment]
Made some changes to the overall statistics dashboard with the range adjustment.
