### ISSUE TITLE
Reduce code redundancy in Spreadsheet download code

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#178]
Nooks and Locations statistics controller has code for downloading a spreadsheet. Both are almost the same.

**Comment by divyanshumehta** [comment]
@shubhpatel108 we can put the code in a module or class in the `lib/` and `reuqire` in the controllers.
What do you say.

**Comment by divyanshumehta** [comment]
@shubhpatel108 I think this issue can be closed now.
