### ISSUE TITLE
Different views for users in different timezones

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#19]
Considering Users will be from different Time zones.The Time selector selects Time in js format.When it gets saved in the database it takes some different value since it is not same as the Ruby date time format. So we need to convert it to Ruby time format before saving it in the database and also suitably display it.[Here ](http://stackoverflow.com/questions/22360332/time-conversion-between-ruby-on-rails-and-javascript-vice-versa)is a method to do it.

**Comment by shubhpatel108** [comment]
Rethinking this as "Different views for users in different timezones"

**Comment by arkokoley** [comment]
@shubhpatel108 Can you please elaborate what does this issue imply? 

> Considering Users will be from different Time zones.The Time selector selects Time in js format.When it gets saved in the database it takes some different value since it is not same as the Ruby date time format. So we need to convert it to Ruby time format before saving it in the database and also suitably display it.Here is a method to do it.

According to @ananyo2012 's description, this is a bug in the conversion of time across Ruby and JS. However, @shubhpatel108 's later edit to the title confuses me. 

"Different views for users in different timezones" can mean that you wish to give the users from different parts of the world, different way of selecting the time. Is my interpretation correct?

**Comment by shubhpatel108** [comment]
@arkokoley: Initial issue was related to a small bug related to timezone conversion. Later on it was converted to a generic feature implementation where - the views are rendered in User's timezone rather than UTC or library's timezone.

**Comment by arkokoley** [comment]
@shubhpatel108 Thanks for the Clarification.

**Comment by arkokoley** [comment]
This issue can be solved by using the method outlined in: 
[http://cowjumpedoverthecommodore64.blogspot.in/2013/03/setting-rails-timezone-to-users.html](http://cowjumpedoverthecommodore64.blogspot.in/2013/03/setting-rails-timezone-to-users.html)

and using the library: [https://bitbucket.org/pellepim/jstimezonedetect](https://bitbucket.org/pellepim/jstimezonedetect)

However, SO pegs jstimezoneDetect as unreliable and other alternatives might need to be considered.
