### ISSUE TITLE
allow admin to set location by typing address

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#199]
in admin dashboard -- location edit view

**Comment by arkokoley** [comment]
Does this mean that the admin would be able to search for an address and then pick that geolocation as the geolocation of the listed location/library?

**Comment by jessyurko** [comment]
Yes, although if there's a library that makes this easy in a slightly different way that's fine too -- just some way of entering location rather than manually dragging a marker on the map.

**Comment by jessyurko** [comment]
I'm getting a Maps API error here --
<img width="1180" alt="screen shot 2017-07-05 at 11 34 29 am" src="https://user-images.githubusercontent.com/1999174/27872207-00bc790e-6176-11e7-84d5-d25a2f74c8b3.png">

**Comment by arkokoley** [comment]
There was a missing environment variable. I have set that now, in the staging server. Please test now. 

Location 2 has been set as Harvard, using the search box 😄

**Comment by jessyurko** [comment]
This looks great!
