### ISSUE TITLE
confirmed reservations not showing up in calendar

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#201]
<img width="1434" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/1999174/25354680/f0072b56-2901-11e7-9e28-8c83f0f973f9.png">
<img width="1421" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/1999174/25354681/f00904f8-2901-11e7-8fe8-4e46c8066e69.png">

**Comment by arkokoley** [comment]
This issue is particularly tricky. It appears sometimes randomly and I can only attribute that to the server ajax request failing. Still would like to know, if it can be reliably reproduced. 

@jessyurko Please try to see if you can reproduce this on the staging server. I couldn't.

**Comment by jessyurko** [comment]
Thanks @arkokoley, I'll check it out and let you know if I still see it.

**Comment by arkokoley** [comment]
@jessyurko should we close this?
