### ISSUE TITLE
A link on homepage to go Admin pannel

### ISSUE THREAD

**Issue by divyanshumehta** [berkmancenter/bookanook#204]
There is no link on the homepage to allow the admin to go to the Admin panel. Currently the admin has to go to the URL add the `/admin` after the URL to go to the admin pannel

**Comment by shubhpatel108** [comment]
@divyanshumehta: Last summer @jessyurko and I discussed on this issue and agreed and not having admin link on the user application. Basically, keeping the admin app separate from the user-facing one though they both run on the same stack. 
Thanks for the PR though! It will help you get started with other issues quickly.
