### ISSUE TITLE
Nook Reservation form broken

### ISSUE THREAD

**Issue by arkokoley** [berkmancenter/bookanook#221]
Reservation form sends request as HTML instead of XHR. This results in the CSRF token being not sent to the server and the following error appears.
![screen shot 2017-07-26 at 20 03 00](https://user-images.githubusercontent.com/1412469/28629182-5879c2da-7244-11e7-8c84-c6cfa99960d9.png)

**Comment by arkokoley** [comment]
@jessyurko Please confirm whether or not the fix works.

**Comment by jessyurko** [comment]
I'm getting the search bar but not seeing any rooms load at all now
<img width="1038" alt="screen shot 2017-07-28 at 9 01 07 am" src="https://user-images.githubusercontent.com/1999174/28718327-64d6caca-7373-11e7-81bc-5861c68622df.png">

**Comment by jessyurko** [comment]
unable to test currently, but moving issue noted above to #224

**Comment by jessyurko** [comment]
Thanks, looks good!

**Comment by arkokoley** [comment]
This error still occurs if nooks are searched with "Any" time.
