### ISSUE TITLE
Don't allow user to modify a confirmed reservation

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#25]
Though UI doesn't provide "Modify" option for confirmed reservation on `/reservations/mine` page, the user can still hit the edit URL of a reservation and update it.

**Comment by shlok007** [comment]
Will this fix the issue?

**Comment by shlok007** [comment]
Travis checks fails as the source link to less-rails gem is deprecated ( #4 ). Should I add the link to the parent repo?

**Comment by shubhpatel108** [comment]
@shlok007 Yes, the changes you suggested may solve the problem. Check if a user is able to modify someone else's request!
You are welcome to send an updated PR for this.

**Comment by shlok007** [comment]
@shubhpatel108 Yeah, currently any user can edit any reservation. This has to be fixed. I'll send an updated PR for this.

**Comment by shlok007** [comment]
Implemented in #143 . Lets close this. :smiley:
