### ISSUE TITLE
Add Reports dashboard to Admin panel

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#31]
Some metrics and statistics can be very important for the admin. Few of them are:
- Confirmed/Total Reservations between 2 dates (in form of PDF report)
- Times for which majority of the reservations are requested for
- Which locations (libraries) are most used
- Most busy months for different libraries
- Busy days in the week

This can help admin gain insights on reservation demands and provide assistant to users on requesting reservations. Sometimes, he/she might also need to submit some of the above reports to the venue facilitator.

**Comment by shubhpatel108** [comment]
We can use Wind Rose chart to show the reservations against the time. For instance:

<img width="530" alt="screen shot 2016-03-07 at 4 49 37 pm" src="https://cloud.githubusercontent.com/assets/4345133/13616228/fee79838-e59e-11e5-8eeb-f2e405dcc314.png">

**Comment by shubhpatel108** [comment]
A simple bar or line graph to show reservation during each month. It depicts the progress made during the year. For example:

<img width="529" alt="screen shot 2016-03-07 at 10 06 24 pm" src="https://cloud.githubusercontent.com/assets/4345133/13616391/ca8dddf8-e59f-11e5-8e49-0cd4c82df7b3.png">

**Comment by shubhpatel108** [comment]
A heat map can give us the comparison between no. of reservations on different days of the week. For instance:

<img width="520" alt="screen shot 2016-03-07 at 5 00 34 pm" src="https://cloud.githubusercontent.com/assets/4345133/13616517/35ce7262-e5a0-11e5-9467-61b63dee6e9b.png">

**Comment by shubhpatel108** [comment]
A filter on the top of this dashboard will help the admin select the locations he/she wants to have in the following graphs. Such detailed report for Nooks might not be needed because for an admin it's about resource management. An overview of reservations requests for each location/library will help him/her to get insights on demand.

**Comment by metalabatharvard** [comment]
These are fantastic ideas for visualizations; the use of a heat map in particular seems really useful and intuitive.

**Comment by shubhpatel108** [comment]
The same visualizations with few changes, can be used for nook based stats also.

**Comment by shubhpatel108** [comment]
Implemented in #144.
