### ISSUE TITLE
Adding Library search functionality according to cities in the Landing Page

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#35]
We can perhaps add a search box to list Libraries according to city in the Landing Page. The city name has to be entered in the search box and it will show the Libraries present in that city. As you type in the city name you will see the available cities through Ajax request.

**Comment by paulinahaduong** [comment]
Interesting idea! When we add Google maps integration, we'll want to explore use cases with multiple libraries to see what the UX questions are.
