### ISSUE TITLE
Add a Trending news page

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#41]
A Trending page is a good way to help users know what are the good locations at a glance or probably where can they find a newly released book they were wanting to read but could not afford to buy or is there some upcoming attractions or just know the Trends in booking.Here are some images to make the picture clearer.
![trending](https://cloud.githubusercontent.com/assets/10486343/13721142/a8994124-e842-11e5-950c-2bbcd7ee2ac0.jpg)

**Comment by ananyo2012** [comment]
On clicking the Trends can be shown in a modal container.
![trending - now](https://cloud.githubusercontent.com/assets/10486343/13721151/ec0444cc-e842-11e5-8453-ed45d96c1e07.jpg)

**Comment by ananyo2012** [comment]
On hovering the mouse pointer on the Trends graph a magnified view can be shown like this
![trending - now-graph](https://cloud.githubusercontent.com/assets/10486343/13721155/0b59deb8-e843-11e5-83c4-96834926b29a.jpg)

**Comment by paulinahaduong** [comment]
Alternatively, Book a nook API could integrate with individual library homepage instead, so as not to create multiple newsfeeds.
