### ISSUE TITLE
Integrate Rubocop for maintaining coding standards

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#46]
It is always a good practice to write cleaner codes.Making the code readable to others is one of the good practices of a open source project.We can integrate [Rubocop](https://github.com/bbatsov/rubocop) to check coding style and metrics in our project encouraging other contributors to write cleaner and readable codes.

**Comment by shubhpatel108** [comment]
Closing, as this is a suggestion on the same line as #45.
