### ISSUE TITLE
Prevent user to cancel reservation within x days of the event

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#48]
The user can unnecessarily block a slot if he/she is unsure of happening of the event. Many users might book the reservation to confirm the nook and cancel before a day or two. The admin should have the power to deny such cancellation if it such cancellation is requested within x days of the event. In other words, allow cancellation until x days before event. 

The value of x may or may not vary across the libraries and can be set by the related admin(s).

**Comment by shlok007** [comment]
Would it be better to specify the value of 'x' in days or hours?

**Comment by jessyurko** [comment]
Short answer, hours.

There are two main use cases -- meeting rooms (bigger events, booked farther in advance) and study rooms (1-2 people, more same-day booking). The policy for meeting rooms is likely to be within x days, and for study rooms within x hours or minutes. At some point, we may formally differentiate between these two types of bookings, but in the meantime, hours would accommodate both scenarios.
