### ISSUE TITLE
Add Links to Nooks from Locations Page of Admin Panel

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#56]
Currently there are no links to Nooks that belongs to a particular Library from the Locations Page in the Admin Panel. It will be handy if the Admin can directly move to the desired nook from the location Page.

**Comment by shubhpatel108** [comment]
@ananyo2012 It seems there are links to the location's nooks. Did you mean this? -

<img width="1108" alt="screen shot 2016-06-01 at 6 12 18 pm" src="https://cloud.githubusercontent.com/assets/4345133/15709837/7e88cd2e-2824-11e6-95ef-fda41f116bae.png">
