### ISSUE TITLE
Provide Authorization using cancancan

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#57]
As mentioned in Issue #52 we should have a Super Admin and other Admins belonging to a Library. So there should be a authorization system to provide authorization to selective resources to different Admins. We can use the [cancancan](https://github.com/CanCanCommunity/cancancan) gem for providing authorizations.

**Comment by shubhpatel108** [comment]
As this is a suggestion on implementing a super admin which is discussed in #52, closing. The reference will help in taking in this idea.

**Comment by ananyo2012** [comment]
@shubhpatel108 The idea is providing authorization to resources, not directly related to the implementation of a Super admin. Further reference [here](http://railscasts.com/episodes/192-authorization-with-cancan?view=asciicast).

**Comment by shubhpatel108** [comment]
Implemented in #107.
