### ISSUE TITLE
Enable reservation form visibility toggle

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#60]
"Fill out a reservation form to book/hide reservation form" text currently does not show/hide the reservation form; the form is always visible.

**Comment by paulinahaduong** [comment]
Seems like it should be a quick fix but currently v. confusing to users.

**Comment by jessyurko** [comment]
<img width="737" alt="screen shot 2016-05-16 at 1 53 16 pm" src="https://cloud.githubusercontent.com/assets/1999174/15298502/9c336b40-1b6d-11e6-9e60-37f3d6de05ae.png">

(Clicking "hide reservation form" link doesn't work; should default to hidden when user opens modal)

**Comment by shubhpatel108** [comment]
Fixed in 1d4e7d86110f157197d573844a0a8cbcda82310c.
