### ISSUE TITLE
Ability to change the date/redo search for a specific room

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#63]
Within the nook's pop-up, at present a user can only change the time of the reservation for that day; can we include a date changer to search within that nook's available for future dates, without redoing the entire search?

**Comment by jessyurko** [comment]
Need to do some more user research on search workflow / legibility to inform this

**Comment by shubhpatel108** [comment]
@jessyurko @paulinahaduong now the reservation form also blocks the closed and reserved slots. And expanded-nook view provides options for the alternate days. Shall we close this?
