### ISSUE TITLE
Update admin-side room reservation date functionality

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#68]
Currently too granular (down to the second) - enable to the half-hour, and streamline it (either via drop-down menus or sliders similar to the user version).

**Comment by jessyurko** [comment]
Currently, can adjust by minute and second 
<img width="1064" alt="screen shot 2016-05-16 at 1 29 10 pm" src="https://cloud.githubusercontent.com/assets/1999174/15298089/9bac31fe-1b6b-11e6-9936-c7f091a01747.png">

All reservations will be on the hour or half hour, so eliminating seconds field and only allowing xx:00 or xx:30 (or even xx:15 to catch any with a different policy) would be simpler for the user.

Might think about a date-time picker that shows both date and time in the same view as well: 
<img width="367" alt="screen shot 2016-05-16 at 1 32 36 pm" src="https://cloud.githubusercontent.com/assets/1999174/15298132/dc599ebc-1b6b-11e6-9447-e08abebb1f55.png"> 
(http://xdsoft.net/jqplugins/datetimepicker/ -- just an example)
