### ISSUE TITLE
No admin sign_in button

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#7]
It would be great if there would be a sign_in button for admin. For now we have to mention the `admin_users` link in the browser. We just have link to the `admin_users_session` route which is missing now.

**Comment by shubhpatel108** [comment]
As suggested by @jessyurko, the admin will know the URL to the admin panel. The idea is to keep the panel and the main application separate. About signing in, the process of it is common for all users. 
Closing.
