### ISSUE TITLE
Admin functionality: flag button for reservations after they've occurred

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#76]
Potentially a dropdown menu, or maybe a field that allows tags (and has drop down suggestions?)

Ex: no-show, late key return, late cancellation, etc.

**Comment by shubhpatel108** [comment]
@paulinahaduong @jessyurko Can we use a text field as 'Remarks'?
Tags is a better option if we are interested in stats like how many people didn't show up.

**Comment by jessyurko** [comment]
We'd ideally have something that would allow an admin to search for all "late cancellations" or "no-shows", so tags would likely be best for this (vs an open text field where different phrasing might be used for the same situation)
