### ISSUE TITLE
Admin functionality: limit user reservations by day

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#79]
Even if users make multiple reservations for the same day, total time of reservations should be able to be limited (default: 2 hour max). If a user makes 1 2hr reservation or 2 1hr reservations, system should notify them that their time has been maxed out.

**Comment by paulinahaduong** [comment]
Admin should be able to override block if making changes to reservations (e.g., if someone nears the end of their reservation and the room is still available, an admin might choose to extend their reservation).

**Comment by shlok007** [comment]
Let me get this straight. The time would be maxed out only for that particular nook, right? The patron would still be able to request reservations in other nooks for that particular day.

**Comment by shubhpatel108** [comment]
This is about limiting the total reservation time of a user across all nooks i.e. 2 hours of reservation(s) on one or multiple nooks.

**Comment by shubhpatel108** [comment]
Implemented the following - User will only be able to make reservation requests of total 2 hours. Admin will still be able to make reservations on behalf of him/her if slots are available. 

@jessyurko shall we have a boolean attribute in nooks which admin can set if he/she wants to allow user to continue sending requests even after exceeding the quota? - sorry for a long sentence.

**Comment by jessyurko** [comment]
If it's straightforward to implement, I could imagine it being useful!
So I'm assuming it would work something like -
- if the attribute is selected, users can continue to make requests with no warning message on their side, even if they exceed 2 hours
- if the attribute is not selected, users will receive some sort of warning message if they try to reserve more than 2  hours

Is that right?

**Comment by shubhpatel108** [comment]
@jessyurko Will have to rethink this as the attribute can be related to a nook or location. But the limit is put on overall hours of reservations requested (doesn't include canceled or rejected).

**Comment by shubhpatel108** [comment]
Presently, I am strictly limiting the user to request when the quota for the requested date is exceeded.
