### ISSUE TITLE
Create downloadable spreadsheets of reservation data

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#82]
Reports should be able to be dynamically created (Qualtrics survey data reporting might be a good example) and downloadable as CSV/Excel (and/or google sheets)

Use case: librarians need to include the number of reservations for the month in the monthly report

**Comment by paulinahaduong** [comment]
Other data librarians are interested in: when are rooms used the most/least, which days are the heaviest (only visible admin-side, not for patron/users).

**Comment by shubhpatel108** [comment]
Implemented in #144.
