### ISSUE TITLE
Provide Progress bar showing filled reservations

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#83]
A circular or horizontal Progress bar can be shown for filled reservations. If N is the max capacity of a nook and x is the no of confirmed reservations. Then a **x/N** can be displayed in the Progress bar.

**Comment by shubhpatel108** [comment]
@ananyo2012 I think N will no. of hours the nook is available on that day. And x is total hours of confirmed reservations. Otherwise, we will not be able to compare them.

**Comment by ananyo2012** [comment]
@shubhpatel108 yes that would be more appropriate. But we will also take care of the fact that a nook will be booked by multiple persons at a time.

**Comment by jessyurko** [comment]
This seems like it could be more useful in the reporting feature rather than admin dashboard.
