### ISSUE TITLE
Rethink date/time on search bar

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#88]
Adding user calendar view probably a good time to revisit the date controls in the user's search bar:
- current mode of selecting date is redundant if nooks are being viewed on a calendar
- "today" vs "future" a little unclear, design could be simplified

**Comment by jessyurko** [comment]
something along these lines:
![simplified search](https://cloud.githubusercontent.com/assets/1999174/15861134/a8a6bd54-2c99-11e6-9394-0968cccab70d.jpg)

**Comment by shubhpatel108** [comment]
Implemented in 1d4e7d86110f157197d573844a0a8cbcda82310c. But we still don't have searching capabilities over nook's capacity.
