### ISSUE TITLE
Setup the app on Heroku 

### ISSUE THREAD

**Issue by shubhpatel108** [berkmancenter/bookanook#91]
As there will be frequent additions, the release of every major feature can be demonstrated on a live version of the application. [Heroku](https://heroku.com) can be used for hosting. 

Is it okay if the application is publicly accessible during the development?

**Comment by jessyurko** [comment]
Yes! That sounds like a great way to test new features. Thanks!

**Comment by shlok007** [comment]
I can work on this :).

**Comment by shubhpatel108** [comment]
@shlok007 great 😃 ! I'll create `heroku` branch and you can send in a PR on it.

**Comment by shubhpatel108** [comment]
Visit the app here: http://bookanook-dev.herokuapp.com/
